repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.4.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
  - id: check-added-large-files

- repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
  rev: v1.5.0
  hooks:
  - id: pretty-format-yaml
    args: [--autofix, --indent, '2']

- repo: https://github.com/PyCQA/isort
  rev: 5.6.4
  hooks:
  - id: isort
    args: [--profile, black]

- repo: https://github.com/psf/black
  rev: 20.8b1
  hooks:
  - id: black

- repo: https://gitlab.com/pycqa/flake8
  rev: 3.8.4
  hooks:
  - id: flake8

- repo: local
  hooks:
  - id: pip-compile
    name: pip-compile
    language: system
    entry: pip-compile
    files: requirements.*
    pass_filenames: false

  - id: terraform-fmt
    name: terraform-fmt
    language: system
    entry: bash -c "cd terraform && ./terraform fmt -recursive"
    files: .*\.tf
    pass_filenames: false

  - id: shellcheck
    name: shellcheck
    language: system
    files: .*\.sh
    entry: ./shellcheck.sh
