#!/bin/bash
set -eux -o pipefail

TF_ROOT=$(dirname $(realpath $0))
ROOT=$(dirname ${TF_ROOT})
DOWNLOADS=${ROOT}/.downloads
TF_FOLDER=${TF_ROOT}/.terraform

if [ ! -f ${TF_FOLDER}/terraform ]; then
    mkdir -p ${TF_FOLDER}
    (cd ${DOWNLOADS} && wget https://releases.hashicorp.com/terraform/0.14.7/terraform_0.14.7_linux_amd64.zip)
    unzip -d ${TF_FOLDER} ${DOWNLOADS}/terraform_0.14.7_linux_amd64.zip
fi

${TF_FOLDER}/terraform $*
