apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../../base
patches:
- patch: |-
    - op: replace
      path: /spec/rules/0/host
      value: flower.prod.on-infra.net
  target:
    name: portal-flower-ingress
- patch: |-
    - op: replace
      path: /spec/rules/0/host
      value: grafana.prod.on-infra.net
  target:
    name: portal-grafana
- patch: |-
    - op: replace
      path: /spec/rules/0/host
      value: portal.prod.on-infra.net
  target:
    name: portal-home-ingress
- patch: |-
    - op: replace
      path: /spec/rules/0/host
      value: longhorn.prod.on-infra.net
  target:
    name: portal-longhorn-operator
- patch: |-
    - op: replace
      path: /spec/rules/0/host
      value: rabbitmq.prod.on-infra.net
  target:
    name: portal-rabbitmq-ingress
- patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/env/0/value
      value: prod.on-infra.net
  target:
    name: portal-home
