apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app: cockroach-operator
  name: cockroach-operator-default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: cockroach-operator-role
subjects:
- kind: ServiceAccount
  name: cockroach-operator-sa
  namespace: default
