apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cockroach-operator-role
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - clusterroles
  verbs:
  - get
  - list
  - delete
- apiGroups:
  - apps
  resources:
  - statefulsets
  verbs:
  - '*'
- apiGroups:
  - apps
  resources:
  - statefulsets/finalizers
  verbs:
  - '*'
- apiGroups:
  - apps
  resources:
  - statefulsets/status
  verbs:
  - '*'
- apiGroups:
  - certificates.k8s.io
  resources:
  - certificatesigningrequests
  verbs:
  - '*'
- apiGroups:
  - certificates.k8s.io
  resources:
  - certificatesigningrequests/approval
  verbs:
  - '*'
- apiGroups:
  - certificates.k8s.io
  resources:
  - certificatesigningrequests/status
  verbs:
  - '*'
- apiGroups:
  - ''
  resources:
  - configmaps
  verbs:
  - '*'
- apiGroups:
  - ''
  resources:
  - nodes
  verbs:
  - get
- apiGroups:
  - ''
  resources:
  - configmaps/status
  verbs:
  - '*'
- apiGroups:
  - ''
  resources:
  - pods/exec
  verbs:
  - '*'
- apiGroups:
  - ''
  resources:
  - secrets
  verbs:
  - '*'
- apiGroups:
  - ''
  resources:
  - services
  verbs:
  - '*'
- apiGroups:
  - ''
  resources:
  - services/finalizers
  verbs:
  - '*'
- apiGroups:
  - ''
  resources:
  - services/status
  verbs:
  - '*'
- apiGroups:
  - crdb.cockroachlabs.com
  resources:
  - crdbclusters
  verbs:
  - '*'
- apiGroups:
  - crdb.cockroachlabs.com
  resources:
  - crdbclusters/status
  verbs:
  - '*'
- apiGroups:
  - policy
  resources:
  - poddisruptionbudgets
  verbs:
  - '*'
- apiGroups:
  - policy
  resources:
  - poddisruptionbudgets/finalizers
  verbs:
  - '*'
- apiGroups:
  - policy
  resources:
  - poddisruptionbudgets/status
  verbs:
  - '*'
- apiGroups:
  - security.openshift.io
  resourceNames:
  - nonroot
  resources:
  - securitycontextconstraints
  verbs:
  - use
