#!/bin/bash
set -eux -o pipefail

CFSSL=.downloads/cfssl_1.5.0_linux_amd64

if [ ! -f $CFSSL ]; then
    mkdir -p .downloads
    wget https://github.com/cloudflare/cfssl/releases/download/v1.5.0/cfssl_1.5.0_linux_amd64 --directory-prefix=.downloads
    chmod +x $CFSSL
fi

$CFSSL $*
