#!/bin/bash
set -eux -o pipefail

CFSSLJSON=.downloads/cfssljson_1.5.0_linux_amd64

if [ ! -f $CFSSLJSON ]; then
    mkdir -p .downloads
    wget https://github.com/cloudflare/cfssl/releases/download/v1.5.0/cfssljson_1.5.0_linux_amd64 --directory-prefix=.downloads
    chmod +x $CFSSLJSON
fi

$CFSSLJSON $*
