apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6IHsiZ2hjci5pbyI6IHsiYXV0aCI6ICJjR0ZzWm5KbGVUcG5hSEJmVG5CelJsaHZaSE5NZDBKMlMyTjRiWEUwTjNSellYSlBPVzlIYUdwV01IUlllRVJvIn19fQ==
kind: Secret
metadata:
  name: infra-github-registry
type: kubernetes.io/dockerconfigjson
