apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    k8s-app: calico-typha
  name: calico-typha
  namespace: kube-system
spec:
  replicas: 2
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      k8s-app: calico-typha
  template:
    metadata:
      annotations:
        cluster-autoscaler.kubernetes.io/safe-to-evict: 'true'
      labels:
        k8s-app: calico-typha
    spec:
      containers:
      - env:
        - name: TYPHA_LOGFILEPATH
          value: none
        - name: TYPHA_LOGSEVERITYSYS
          value: none
        - name: TYPHA_LOGSEVERITYSCREEN
          value: Debug
        - name: TYPHA_CONNECTIONREBALANCINGMODE
          value: kubernetes
        - name: TYPHA_DATASTORETYPE
          value: kubernetes
        - name: TYPHA_HEALTHENABLED
          value: 'true'
        - name: TYPHA_CAFILE
          value: /calico-typha-ca/typha-ca.pem
        - name: TYPHA_CLIENTCN
          value: calico-node
        - name: TYPHA_SERVERCERTFILE
          value: /calico-typha-certs/typha.pem
        - name: TYPHA_SERVERKEYFILE
          value: /calico-typha-certs/typha-key.pem
        image: calico/typha:v3.8.0
        livenessProbe:
          httpGet:
            host: localhost
            path: /liveness
            port: 9098
          initialDelaySeconds: 30
          periodSeconds: 30
        name: calico-typha
        ports:
        - containerPort: 5473
          name: calico-typha
          protocol: TCP
        readinessProbe:
          httpGet:
            host: localhost
            path: /readiness
            port: 9098
          periodSeconds: 10
        volumeMounts:
        - mountPath: /calico-typha-ca
          name: calico-typha-ca
          readOnly: true
        - mountPath: /calico-typha-certs
          name: calico-typha-certs
          readOnly: true
      hostNetwork: true
      priorityClassName: system-cluster-critical
      serviceAccountName: calico-typha
      tolerations:
      - key: CriticalAddonsOnly
        operator: Exists
      volumes:
      - configMap:
          name: calico-typha-ca
        name: calico-typha-ca
      - name: calico-typha-certs
        secret:
          secretName: calico-typha-certs
