apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: calico-cni
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: calico-cni
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: calico-cni
